export type WindowsZoneName =
  | 'Dateline Standard Time'
  | 'UTC-11'
  | 'Aleutian Standard Time'
  | 'Hawaiian Standard Time'
  | 'Marquesas Standard Time'
  | 'Alaskan Standard Time'
  | 'UTC-09'
  | 'Pacific Standard Time (Mexico)'
  | 'UTC-08'
  | 'Pacific Standard Time'
  | 'US Mountain Standard Time'
  | 'Mountain Standard Time (Mexico)'
  | 'Mountain Standard Time'
  | 'Yukon Standard Time'
  | 'Central America Standard Time'
  | 'Central Standard Time'
  | 'Easter Island Standard Time'
  | 'Central Standard Time (Mexico)'
  | 'Canada Central Standard Time'
  | 'SA Pacific Standard Time'
  | 'Eastern Standard Time (Mexico)'
  | 'Eastern Standard Time'
  | 'Haiti Standard Time'
  | 'Cuba Standard Time'
  | 'US Eastern Standard Time'
  | 'Turks And Caicos Standard Time'
  | 'Paraguay Standard Time'
  | 'Atlantic Standard Time'
  | 'Venezuela Standard Time'
  | 'Central Brazilian Standard Time'
  | 'SA Western Standard Time'
  | 'Pacific SA Standard Time'
  | 'Newfoundland Standard Time'
  | 'Tocantins Standard Time'
  | 'E. South America Standard Time'
  | 'SA Eastern Standard Time'
  | 'Argentina Standard Time'
  | 'Greenland Standard Time'
  | 'Montevideo Standard Time'
  | 'Magallanes Standard Time'
  | 'Saint Pierre Standard Time'
  | 'Bahia Standard Time'
  | 'UTC-02'
  | 'Azores Standard Time'
  | 'Cape Verde Standard Time'
  | 'UTC'
  | 'GMT Standard Time'
  | 'Greenwich Standard Time'
  | 'Sao Tome Standard Time'
  | 'Morocco Standard Time'
  | 'W. Europe Standard Time'
  | 'Central Europe Standard Time'
  | 'Romance Standard Time'
  | 'Central European Standard Time'
  | 'W. Central Africa Standard Time'
  | 'Jordan Standard Time'
  | 'GTB Standard Time'
  | 'Middle East Standard Time'
  | 'Egypt Standard Time'
  | 'E. Europe Standard Time'
  | 'Syria Standard Time'
  | 'West Bank Standard Time'
  | 'South Africa Standard Time'
  | 'FLE Standard Time'
  | 'Israel Standard Time'
  | 'Kaliningrad Standard Time'
  | 'Sudan Standard Time'
  | 'Libya Standard Time'
  | 'Namibia Standard Time'
  | 'Arabic Standard Time'
  | 'Turkey Standard Time'
  | 'Arab Standard Time'
  | 'Belarus Standard Time'
  | 'Russian Standard Time'
  | 'E. Africa Standard Time'
  | 'Iran Standard Time'
  | 'Arabian Standard Time'
  | 'Astrakhan Standard Time'
  | 'Azerbaijan Standard Time'
  | 'Russia Time Zone 3'
  | 'Mauritius Standard Time'
  | 'Saratov Standard Time'
  | 'Georgian Standard Time'
  | 'Volgograd Standard Time'
  | 'Caucasus Standard Time'
  | 'Afghanistan Standard Time'
  | 'West Asia Standard Time'
  | 'Ekaterinburg Standard Time'
  | 'Pakistan Standard Time'
  | 'Qyzylorda Standard Time'
  | 'India Standard Time'
  | 'Sri Lanka Standard Time'
  | 'Nepal Standard Time'
  | 'Central Asia Standard Time'
  | 'Bangladesh Standard Time'
  | 'Omsk Standard Time'
  | 'Myanmar Standard Time'
  | 'SE Asia Standard Time'
  | 'Altai Standard Time'
  | 'W. Mongolia Standard Time'
  | 'North Asia Standard Time'
  | 'N. Central Asia Standard Time'
  | 'Tomsk Standard Time'
  | 'China Standard Time'
  | 'North Asia East Standard Time'
  | 'Singapore Standard Time'
  | 'W. Australia Standard Time'
  | 'Taipei Standard Time'
  | 'Ulaanbaatar Standard Time'
  | 'Aus Central W. Standard Time'
  | 'Transbaikal Standard Time'
  | 'Tokyo Standard Time'
  | 'North Korea Standard Time'
  | 'Korea Standard Time'
  | 'Yakutsk Standard Time'
  | 'Cen. Australia Standard Time'
  | 'AUS Central Standard Time'
  | 'E. Australia Standard Time'
  | 'AUS Eastern Standard Time'
  | 'West Pacific Standard Time'
  | 'Tasmania Standard Time'
  | 'Vladivostok Standard Time'
  | 'Lord Howe Standard Time'
  | 'Bougainville Standard Time'
  | 'Russia Time Zone 10'
  | 'Magadan Standard Time'
  | 'Norfolk Standard Time'
  | 'Sakhalin Standard Time'
  | 'Central Pacific Standard Time'
  | 'Russia Time Zone 11'
  | 'New Zealand Standard Time'
  | 'UTC+12'
  | 'Fiji Standard Time'
  | 'Chatham Islands Standard Time'
  | 'UTC+13'
  | 'Tonga Standard Time'
  | 'Samoa Standard Time'
  | 'Line Islands Standard Time';

export type Territory =
  | '001'
  | 'ZZ'
  | 'AS'
  | 'NU'
  | 'UM'
  | 'US'
  | 'CK'
  | 'PF'
  | 'MX'
  | 'PN'
  | 'CA'
  | 'BZ'
  | 'CR'
  | 'EC'
  | 'GT'
  | 'HN'
  | 'NI'
  | 'SV'
  | 'CL'
  | 'BR'
  | 'CO'
  | 'JM'
  | 'KY'
  | 'PA'
  | 'PE'
  | 'BS'
  | 'HT'
  | 'CU'
  | 'TC'
  | 'PY'
  | 'BM'
  | 'GL'
  | 'VE'
  | 'AG'
  | 'AI'
  | 'AW'
  | 'BB'
  | 'BL'
  | 'BO'
  | 'BQ'
  | 'CW'
  | 'DM'
  | 'DO'
  | 'GD'
  | 'GP'
  | 'GY'
  | 'KN'
  | 'LC'
  | 'MF'
  | 'MQ'
  | 'MS'
  | 'PR'
  | 'SX'
  | 'TT'
  | 'VC'
  | 'VG'
  | 'VI'
  | 'AQ'
  | 'FK'
  | 'GF'
  | 'SR'
  | 'AR'
  | 'UY'
  | 'PM'
  | 'GS'
  | 'PT'
  | 'CV'
  | 'ES'
  | 'FO'
  | 'GB'
  | 'GG'
  | 'IE'
  | 'IM'
  | 'JE'
  | 'BF'
  | 'CI'
  | 'GH'
  | 'GM'
  | 'GN'
  | 'GW'
  | 'IS'
  | 'LR'
  | 'ML'
  | 'MR'
  | 'SH'
  | 'SL'
  | 'SN'
  | 'TG'
  | 'ST'
  | 'EH'
  | 'MA'
  | 'AD'
  | 'AT'
  | 'CH'
  | 'DE'
  | 'GI'
  | 'IT'
  | 'LI'
  | 'LU'
  | 'MC'
  | 'MT'
  | 'NL'
  | 'NO'
  | 'SE'
  | 'SJ'
  | 'SM'
  | 'VA'
  | 'AL'
  | 'CZ'
  | 'HU'
  | 'ME'
  | 'RS'
  | 'SI'
  | 'SK'
  | 'BE'
  | 'DK'
  | 'FR'
  | 'BA'
  | 'HR'
  | 'MK'
  | 'PL'
  | 'AO'
  | 'BJ'
  | 'CD'
  | 'CF'
  | 'CG'
  | 'CM'
  | 'DZ'
  | 'GA'
  | 'GQ'
  | 'NE'
  | 'NG'
  | 'TD'
  | 'TN'
  | 'JO'
  | 'CY'
  | 'GR'
  | 'RO'
  | 'LB'
  | 'EG'
  | 'MD'
  | 'SY'
  | 'PS'
  | 'BI'
  | 'BW'
  | 'LS'
  | 'MW'
  | 'MZ'
  | 'RW'
  | 'SS'
  | 'SZ'
  | 'ZA'
  | 'ZM'
  | 'ZW'
  | 'AX'
  | 'BG'
  | 'EE'
  | 'FI'
  | 'LT'
  | 'LV'
  | 'UA'
  | 'IL'
  | 'RU'
  | 'SD'
  | 'LY'
  | 'NA'
  | 'IQ'
  | 'TR'
  | 'BH'
  | 'KW'
  | 'QA'
  | 'SA'
  | 'YE'
  | 'BY'
  | 'DJ'
  | 'ER'
  | 'ET'
  | 'KE'
  | 'KM'
  | 'MG'
  | 'SO'
  | 'TZ'
  | 'UG'
  | 'YT'
  | 'IR'
  | 'AE'
  | 'OM'
  | 'AZ'
  | 'MU'
  | 'RE'
  | 'SC'
  | 'GE'
  | 'AM'
  | 'AF'
  | 'KZ'
  | 'MV'
  | 'TF'
  | 'TJ'
  | 'TM'
  | 'UZ'
  | 'PK'
  | 'IN'
  | 'LK'
  | 'NP'
  | 'CN'
  | 'IO'
  | 'KG'
  | 'BD'
  | 'BT'
  | 'CC'
  | 'MM'
  | 'CX'
  | 'ID'
  | 'KH'
  | 'LA'
  | 'TH'
  | 'VN'
  | 'MN'
  | 'HK'
  | 'MO'
  | 'BN'
  | 'MY'
  | 'PH'
  | 'SG'
  | 'AU'
  | 'TW'
  | 'JP'
  | 'PW'
  | 'TL'
  | 'KP'
  | 'KR'
  | 'FM'
  | 'GU'
  | 'MP'
  | 'PG'
  | 'NF'
  | 'NC'
  | 'SB'
  | 'VU'
  | 'NZ'
  | 'KI'
  | 'MH'
  | 'NR'
  | 'TV'
  | 'WF'
  | 'FJ'
  | 'TK'
  | 'TO'
  | 'WS';

export type IanaName =
  | 'Etc/GMT+12'
  | 'Etc/GMT+11'
  | 'Pacific/Pago_Pago'
  | 'Pacific/Niue'
  | 'Pacific/Midway'
  | 'America/Adak'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'Pacific/Tahiti'
  | 'Pacific/Johnston'
  | 'Etc/GMT+10'
  | 'Pacific/Marquesas'
  | 'America/Anchorage'
  | 'America/Juneau'
  | 'America/Metlakatla'
  | 'America/Nome'
  | 'America/Sitka'
  | 'America/Yakutat'
  | 'Etc/GMT+9'
  | 'Pacific/Gambier'
  | 'America/Tijuana'
  | 'America/Santa_Isabel'
  | 'Etc/GMT+8'
  | 'Pacific/Pitcairn'
  | 'America/Los_Angeles'
  | 'America/Vancouver'
  | 'PST8PDT'
  | 'America/Phoenix'
  | 'America/Hermosillo'
  | 'Etc/GMT+7'
  | 'America/Chihuahua'
  | 'America/Mazatlan'
  | 'America/Denver'
  | 'America/Edmonton'
  | 'America/Cambridge_Bay'
  | 'America/Inuvik'
  | 'America/Yellowknife'
  | 'America/Ojinaga'
  | 'America/Boise'
  | 'MST7MDT'
  | 'America/Whitehorse'
  | 'America/Creston'
  | 'America/Dawson'
  | 'America/Dawson_Creek'
  | 'America/Fort_Nelson'
  | 'America/Guatemala'
  | 'America/Belize'
  | 'America/Costa_Rica'
  | 'Pacific/Galapagos'
  | 'America/Tegucigalpa'
  | 'America/Managua'
  | 'America/El_Salvador'
  | 'Etc/GMT+6'
  | 'America/Chicago'
  | 'America/Winnipeg'
  | 'America/Rainy_River'
  | 'America/Rankin_Inlet'
  | 'America/Resolute'
  | 'America/Matamoros'
  | 'America/Indiana/Knox'
  | 'America/Indiana/Tell_City'
  | 'America/Menominee'
  | 'America/North_Dakota/Beulah'
  | 'America/North_Dakota/Center'
  | 'America/North_Dakota/New_Salem'
  | 'CST6CDT'
  | 'Pacific/Easter'
  | 'America/Mexico_City'
  | 'America/Bahia_Banderas'
  | 'America/Merida'
  | 'America/Monterrey'
  | 'America/Regina'
  | 'America/Swift_Current'
  | 'America/Bogota'
  | 'America/Rio_Branco'
  | 'America/Eirunepe'
  | 'America/Coral_Harbour'
  | 'America/Guayaquil'
  | 'America/Jamaica'
  | 'America/Cayman'
  | 'America/Panama'
  | 'America/Lima'
  | 'Etc/GMT+5'
  | 'America/Cancun'
  | 'America/New_York'
  | 'America/Nassau'
  | 'America/Toronto'
  | 'America/Iqaluit'
  | 'America/Montreal'
  | 'America/Nipigon'
  | 'America/Pangnirtung'
  | 'America/Thunder_Bay'
  | 'America/Detroit'
  | 'America/Indiana/Petersburg'
  | 'America/Indiana/Vincennes'
  | 'America/Indiana/Winamac'
  | 'America/Kentucky/Monticello'
  | 'America/Louisville'
  | 'EST5EDT'
  | 'America/Port-au-Prince'
  | 'America/Havana'
  | 'America/Indianapolis'
  | 'America/Indiana/Marengo'
  | 'America/Indiana/Vevay'
  | 'America/Grand_Turk'
  | 'America/Asuncion'
  | 'America/Halifax'
  | 'Atlantic/Bermuda'
  | 'America/Glace_Bay'
  | 'America/Goose_Bay'
  | 'America/Moncton'
  | 'America/Thule'
  | 'America/Caracas'
  | 'America/Cuiaba'
  | 'America/Campo_Grande'
  | 'America/La_Paz'
  | 'America/Antigua'
  | 'America/Anguilla'
  | 'America/Aruba'
  | 'America/Barbados'
  | 'America/St_Barthelemy'
  | 'America/Kralendijk'
  | 'America/Manaus'
  | 'America/Boa_Vista'
  | 'America/Porto_Velho'
  | 'America/Blanc-Sablon'
  | 'America/Curacao'
  | 'America/Dominica'
  | 'America/Santo_Domingo'
  | 'America/Grenada'
  | 'America/Guadeloupe'
  | 'America/Guyana'
  | 'America/St_Kitts'
  | 'America/St_Lucia'
  | 'America/Marigot'
  | 'America/Martinique'
  | 'America/Montserrat'
  | 'America/Puerto_Rico'
  | 'America/Lower_Princes'
  | 'America/Port_of_Spain'
  | 'America/St_Vincent'
  | 'America/Tortola'
  | 'America/St_Thomas'
  | 'Etc/GMT+4'
  | 'America/Santiago'
  | 'America/St_Johns'
  | 'America/Araguaina'
  | 'America/Sao_Paulo'
  | 'America/Cayenne'
  | 'Antarctica/Rothera'
  | 'Antarctica/Palmer'
  | 'America/Fortaleza'
  | 'America/Belem'
  | 'America/Maceio'
  | 'America/Recife'
  | 'America/Santarem'
  | 'Atlantic/Stanley'
  | 'America/Paramaribo'
  | 'Etc/GMT+3'
  | 'America/Buenos_Aires'
  | 'America/Argentina/La_Rioja'
  | 'America/Argentina/Rio_Gallegos'
  | 'America/Argentina/Salta'
  | 'America/Argentina/San_Juan'
  | 'America/Argentina/San_Luis'
  | 'America/Argentina/Tucuman'
  | 'America/Argentina/Ushuaia'
  | 'America/Catamarca'
  | 'America/Cordoba'
  | 'America/Jujuy'
  | 'America/Mendoza'
  | 'America/Godthab'
  | 'America/Montevideo'
  | 'America/Punta_Arenas'
  | 'America/Miquelon'
  | 'America/Bahia'
  | 'Etc/GMT+2'
  | 'America/Noronha'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'America/Scoresbysund'
  | 'Atlantic/Cape_Verde'
  | 'Etc/GMT+1'
  | 'Etc/GMT'
  | 'America/Danmarkshavn'
  | 'Etc/UTC'
  | 'Europe/London'
  | 'Atlantic/Canary'
  | 'Atlantic/Faeroe'
  | 'Europe/Guernsey'
  | 'Europe/Dublin'
  | 'Europe/Isle_of_Man'
  | 'Europe/Jersey'
  | 'Europe/Lisbon'
  | 'Atlantic/Madeira'
  | 'Atlantic/Reykjavik'
  | 'Africa/Ouagadougou'
  | 'Africa/Abidjan'
  | 'Africa/Accra'
  | 'Africa/Banjul'
  | 'Africa/Conakry'
  | 'Africa/Bissau'
  | 'Africa/Monrovia'
  | 'Africa/Bamako'
  | 'Africa/Nouakchott'
  | 'Atlantic/St_Helena'
  | 'Africa/Freetown'
  | 'Africa/Dakar'
  | 'Africa/Lome'
  | 'Africa/Sao_Tome'
  | 'Africa/Casablanca'
  | 'Africa/El_Aaiun'
  | 'Europe/Berlin'
  | 'Europe/Andorra'
  | 'Europe/Vienna'
  | 'Europe/Zurich'
  | 'Europe/Busingen'
  | 'Europe/Gibraltar'
  | 'Europe/Rome'
  | 'Europe/Vaduz'
  | 'Europe/Luxembourg'
  | 'Europe/Monaco'
  | 'Europe/Malta'
  | 'Europe/Amsterdam'
  | 'Europe/Oslo'
  | 'Europe/Stockholm'
  | 'Arctic/Longyearbyen'
  | 'Europe/San_Marino'
  | 'Europe/Vatican'
  | 'Europe/Budapest'
  | 'Europe/Tirane'
  | 'Europe/Prague'
  | 'Europe/Podgorica'
  | 'Europe/Belgrade'
  | 'Europe/Ljubljana'
  | 'Europe/Bratislava'
  | 'Europe/Paris'
  | 'Europe/Brussels'
  | 'Europe/Copenhagen'
  | 'Europe/Madrid'
  | 'Africa/Ceuta'
  | 'Europe/Warsaw'
  | 'Europe/Sarajevo'
  | 'Europe/Zagreb'
  | 'Europe/Skopje'
  | 'Africa/Lagos'
  | 'Africa/Luanda'
  | 'Africa/Porto-Novo'
  | 'Africa/Kinshasa'
  | 'Africa/Bangui'
  | 'Africa/Brazzaville'
  | 'Africa/Douala'
  | 'Africa/Algiers'
  | 'Africa/Libreville'
  | 'Africa/Malabo'
  | 'Africa/Niamey'
  | 'Africa/Ndjamena'
  | 'Africa/Tunis'
  | 'Etc/GMT-1'
  | 'Asia/Amman'
  | 'Europe/Bucharest'
  | 'Asia/Nicosia'
  | 'Asia/Famagusta'
  | 'Europe/Athens'
  | 'Asia/Beirut'
  | 'Africa/Cairo'
  | 'Europe/Chisinau'
  | 'Asia/Damascus'
  | 'Asia/Hebron'
  | 'Asia/Gaza'
  | 'Africa/Johannesburg'
  | 'Africa/Bujumbura'
  | 'Africa/Gaborone'
  | 'Africa/Lubumbashi'
  | 'Africa/Maseru'
  | 'Africa/Blantyre'
  | 'Africa/Maputo'
  | 'Africa/Kigali'
  | 'Africa/Juba'
  | 'Africa/Mbabane'
  | 'Africa/Lusaka'
  | 'Africa/Harare'
  | 'Etc/GMT-2'
  | 'Europe/Kiev'
  | 'Europe/Mariehamn'
  | 'Europe/Sofia'
  | 'Europe/Tallinn'
  | 'Europe/Helsinki'
  | 'Europe/Vilnius'
  | 'Europe/Riga'
  | 'Europe/Uzhgorod'
  | 'Europe/Zaporozhye'
  | 'Asia/Jerusalem'
  | 'Europe/Kaliningrad'
  | 'Africa/Khartoum'
  | 'Africa/Tripoli'
  | 'Africa/Windhoek'
  | 'Asia/Baghdad'
  | 'Europe/Istanbul'
  | 'Asia/Riyadh'
  | 'Asia/Bahrain'
  | 'Asia/Kuwait'
  | 'Asia/Qatar'
  | 'Asia/Aden'
  | 'Europe/Minsk'
  | 'Europe/Moscow'
  | 'Europe/Kirov'
  | 'Europe/Simferopol'
  | 'Africa/Nairobi'
  | 'Antarctica/Syowa'
  | 'Africa/Djibouti'
  | 'Africa/Asmera'
  | 'Africa/Addis_Ababa'
  | 'Indian/Comoro'
  | 'Indian/Antananarivo'
  | 'Africa/Mogadishu'
  | 'Africa/Dar_es_Salaam'
  | 'Africa/Kampala'
  | 'Indian/Mayotte'
  | 'Etc/GMT-3'
  | 'Asia/Tehran'
  | 'Asia/Dubai'
  | 'Asia/Muscat'
  | 'Etc/GMT-4'
  | 'Europe/Astrakhan'
  | 'Europe/Ulyanovsk'
  | 'Asia/Baku'
  | 'Europe/Samara'
  | 'Indian/Mauritius'
  | 'Indian/Reunion'
  | 'Indian/Mahe'
  | 'Europe/Saratov'
  | 'Asia/Tbilisi'
  | 'Europe/Volgograd'
  | 'Asia/Yerevan'
  | 'Asia/Kabul'
  | 'Asia/Tashkent'
  | 'Antarctica/Mawson'
  | 'Asia/Oral'
  | 'Asia/Aqtau'
  | 'Asia/Aqtobe'
  | 'Asia/Atyrau'
  | 'Indian/Maldives'
  | 'Indian/Kerguelen'
  | 'Asia/Dushanbe'
  | 'Asia/Ashgabat'
  | 'Asia/Samarkand'
  | 'Etc/GMT-5'
  | 'Asia/Yekaterinburg'
  | 'Asia/Karachi'
  | 'Asia/Qyzylorda'
  | 'Asia/Calcutta'
  | 'Asia/Colombo'
  | 'Asia/Katmandu'
  | 'Asia/Almaty'
  | 'Antarctica/Vostok'
  | 'Asia/Urumqi'
  | 'Indian/Chagos'
  | 'Asia/Bishkek'
  | 'Asia/Qostanay'
  | 'Etc/GMT-6'
  | 'Asia/Dhaka'
  | 'Asia/Thimphu'
  | 'Asia/Omsk'
  | 'Asia/Rangoon'
  | 'Indian/Cocos'
  | 'Asia/Bangkok'
  | 'Antarctica/Davis'
  | 'Indian/Christmas'
  | 'Asia/Jakarta'
  | 'Asia/Pontianak'
  | 'Asia/Phnom_Penh'
  | 'Asia/Vientiane'
  | 'Asia/Saigon'
  | 'Etc/GMT-7'
  | 'Asia/Barnaul'
  | 'Asia/Hovd'
  | 'Asia/Krasnoyarsk'
  | 'Asia/Novokuznetsk'
  | 'Asia/Novosibirsk'
  | 'Asia/Tomsk'
  | 'Asia/Shanghai'
  | 'Asia/Hong_Kong'
  | 'Asia/Macau'
  | 'Asia/Irkutsk'
  | 'Asia/Singapore'
  | 'Asia/Brunei'
  | 'Asia/Makassar'
  | 'Asia/Kuala_Lumpur'
  | 'Asia/Kuching'
  | 'Asia/Manila'
  | 'Etc/GMT-8'
  | 'Australia/Perth'
  | 'Asia/Taipei'
  | 'Asia/Ulaanbaatar'
  | 'Asia/Choibalsan'
  | 'Australia/Eucla'
  | 'Asia/Chita'
  | 'Asia/Tokyo'
  | 'Asia/Jayapura'
  | 'Pacific/Palau'
  | 'Asia/Dili'
  | 'Etc/GMT-9'
  | 'Asia/Pyongyang'
  | 'Asia/Seoul'
  | 'Asia/Yakutsk'
  | 'Asia/Khandyga'
  | 'Australia/Adelaide'
  | 'Australia/Broken_Hill'
  | 'Australia/Darwin'
  | 'Australia/Brisbane'
  | 'Australia/Lindeman'
  | 'Australia/Sydney'
  | 'Australia/Melbourne'
  | 'Pacific/Port_Moresby'
  | 'Antarctica/DumontDUrville'
  | 'Pacific/Truk'
  | 'Pacific/Guam'
  | 'Pacific/Saipan'
  | 'Etc/GMT-10'
  | 'Australia/Hobart'
  | 'Australia/Currie'
  | 'Antarctica/Macquarie'
  | 'Asia/Vladivostok'
  | 'Asia/Ust-Nera'
  | 'Australia/Lord_Howe'
  | 'Pacific/Bougainville'
  | 'Asia/Srednekolymsk'
  | 'Asia/Magadan'
  | 'Pacific/Norfolk'
  | 'Asia/Sakhalin'
  | 'Pacific/Guadalcanal'
  | 'Antarctica/Casey'
  | 'Pacific/Ponape'
  | 'Pacific/Kosrae'
  | 'Pacific/Noumea'
  | 'Pacific/Efate'
  | 'Etc/GMT-11'
  | 'Asia/Kamchatka'
  | 'Asia/Anadyr'
  | 'Pacific/Auckland'
  | 'Antarctica/McMurdo'
  | 'Etc/GMT-12'
  | 'Pacific/Tarawa'
  | 'Pacific/Majuro'
  | 'Pacific/Kwajalein'
  | 'Pacific/Nauru'
  | 'Pacific/Funafuti'
  | 'Pacific/Wake'
  | 'Pacific/Wallis'
  | 'Pacific/Fiji'
  | 'Pacific/Chatham'
  | 'Etc/GMT-13'
  | 'Pacific/Enderbury'
  | 'Pacific/Fakaofo'
  | 'Pacific/Tongatapu'
  | 'Pacific/Apia'
  | 'Pacific/Kiritimati'
  | 'Etc/GMT-14'
  | 'Antarctica/Troll'
  | 'America/Argentina/Buenos_Aires'
  | 'America/Argentina/Cordoba'
  | 'America/Rosario'
  | 'America/Argentina/Catamarca'
  | 'America/Argentina/ComodRivadavia'
  | 'America/Argentina/Jujuy'
  | 'America/Argentina/Mendoza'
  | 'Pacific/Samoa'
  | 'US/Samoa'
  | 'Australia/South'
  | 'Australia/Yancowinna'
  | 'Australia/Queensland'
  | 'Australia/North'
  | 'Australia/Tasmania'
  | 'Australia/LHI'
  | 'Australia/Victoria'
  | 'Australia/West'
  | 'Australia/ACT'
  | 'Australia/Canberra'
  | 'Australia/NSW'
  | 'Asia/Dacca'
  | 'Brazil/DeNoronha'
  | 'Brazil/West'
  | 'America/Porto_Acre'
  | 'Brazil/Acre'
  | 'Brazil/East'
  | 'Asia/Thimbu'
  | 'Canada/Mountain'
  | 'Canada/Atlantic'
  | 'Canada/East-Saskatchewan'
  | 'Canada/Saskatchewan'
  | 'Canada/Newfoundland'
  | 'Canada/Eastern'
  | 'Canada/Pacific'
  | 'Canada/Central'
  | 'Canada/Yukon'
  | 'America/Atikokan'
  | 'Chile/EasterIsland'
  | 'Chile/Continental'
  | 'Asia/Chongqing'
  | 'Asia/Chungking'
  | 'Asia/Harbin'
  | 'PRC'
  | 'Asia/Kashgar'
  | 'Cuba'
  | 'Europe/Nicosia'
  | 'Egypt'
  | 'Africa/Asmara'
  | 'Pacific/Pohnpei'
  | 'Pacific/Chuuk'
  | 'Pacific/Yap'
  | 'Atlantic/Faroe'
  | 'Europe/Belfast'
  | 'GB'
  | 'GB-Eire'
  | 'America/Nuuk'
  | 'Etc/GMT+0'
  | 'Etc/GMT-0'
  | 'Etc/GMT0'
  | 'Etc/Greenwich'
  | 'GMT'
  | 'GMT+0'
  | 'GMT-0'
  | 'GMT0'
  | 'Greenwich'
  | 'Hongkong'
  | 'Asia/Ujung_Pandang'
  | 'Eire'
  | 'Asia/Kolkata'
  | 'Iran'
  | 'Iceland'
  | 'Asia/Tel_Aviv'
  | 'Israel'
  | 'Jamaica'
  | 'Japan'
  | 'ROK'
  | 'Libya'
  | 'Europe/Tiraspol'
  | 'Kwajalein'
  | 'Africa/Timbuktu'
  | 'Asia/Yangon'
  | 'Asia/Ulan_Bator'
  | 'Asia/Macao'
  | 'Mexico/General'
  | 'Mexico/BajaSur'
  | 'America/Ensenada'
  | 'Mexico/BajaNorte'
  | 'Asia/Kathmandu'
  | 'Antarctica/South_Pole'
  | 'NZ'
  | 'NZ-CHAT'
  | 'Poland'
  | 'Portugal'
  | 'W-SU'
  | 'Singapore'
  | 'Atlantic/Jan_Mayen'
  | 'Asia/Ashkhabad'
  | 'Asia/Istanbul'
  | 'Turkey'
  | 'ROC'
  | 'Etc/Unknown'
  | 'America/Atka'
  | 'US/Aleutian'
  | 'US/Alaska'
  | 'US/Central'
  | 'America/Shiprock'
  | 'Navajo'
  | 'US/Mountain'
  | 'US/Michigan'
  | 'US/Hawaii'
  | 'America/Fort_Wayne'
  | 'America/Indiana/Indianapolis'
  | 'US/East-Indiana'
  | 'America/Knox_IN'
  | 'US/Indiana-Starke'
  | 'US/Pacific'
  | 'US/Pacific-New'
  | 'America/Kentucky/Louisville'
  | 'US/Eastern'
  | 'US/Arizona'
  | 'Etc/UCT'
  | 'Etc/Universal'
  | 'Etc/Zulu'
  | 'UCT'
  | 'UTC'
  | 'Universal'
  | 'Zulu'
  | 'EST'
  | 'MST'
  | 'HST'
  | 'America/Virgin'
  | 'Asia/Ho_Chi_Minh';
